homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 284
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  auth_providers:
    - type: legacy_api_password
    - type: homeassistant

auth:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

configurator:

#Configuration Panel Enabler
config:

cloud:
  alexa:
    filter:
      include_domains:
        - cover
        - fan
        - lock
        - switch
        - script
      exclude_domains:
        - group
        - media_player
        - light
        - scene
        - automation
      include_entities:
        - light.ge_basement_dimmer_level
        - media_player.denon_avrx4400h
      exclude_entities:
        - cover.living_room_shade_switch
        - switch.living_room_shade_switch
    entity_config:
      cover.living_room_shade_level:
        name: Living Room Shade
        description: The shade in the living room
        display_categories: door
      light.ge_basement_dimmer_level:
        name: Basement Dimmer
        description: The dimmer switch in the basement
        display_categories: light
      light.cabinet_lights:
        name: Cabinet Lights
        description: "The undercabinet lights"
        display_categories: light
      script.denon_apple_tv_4k:
        name: "Apple TV"
        description: "Apple TV input"
      script.denon_blu_ray:
        name: "Blu Ray"
        description: "Blu Ray input"
      script.denon_bluetooth:
        name: "Bluetooth"
        description: "Bluetooth input"
      script.denon_nintendo_switch:
        name: "Nintendo Switch"
        description: "Nintendo Switch input"
      script.denon_ps4:
        name: "Playstation"
        description: "PS4 input"
      script.denon_vr:
        name: "VR"
        description: "VR input"
      media_player.denon_avrx4400h:
        name: "Receiver"
        description: "Receiver"

  google_actions:
    filter:
      include_domains:
        - cover 
        - fan
        - lock
        - switch
        - script
      exclude_domains:
        - group
        - media_player
        - light
        - automation
        - scene
      include_entities:
        - light.ge_basement_dimmer_level
        - media_player.denon_avrx4400h
      exclude_entities:
        - cover.living_room_shade_switch
        - switch.living_room_shade_switch
    entity_config:
      cover.living_room_shade_level:
        name: "Living Room Shade"
        aliases: "Living Room Blinds"
      light.ge_basement_dimmer_level:
        name: "Basement Dimmer"
      light.cabinet_lights:
        name: "Cabinet Lights"
      script.denon_apple_tv_4k:
        name: "Apple TV"
      script.denon_blu_ray:
        name: "Blu Ray"
      script.denon_bluetooth:
        name: "Bluetooth"
      script.denon_nintendo_switch:
        name: "Nintendo Switch"
      script.denon_ps4:
        name: "Playstation"
      script.denon_vr:
        name: "VR"
      media_player.denon_avrx4400h:
        name: "Receiver"
tts:
  - platform: google

cast:
  media_player:
  - host: 192.168.1.31
  - host: 192.168.1.32

media_player:
  - platform: denonavr
    host: 192.168.1.35
    name: 'Denon AVR-X4400H'
    # show_all_sources: True

#Map Panel Enabler
map:

http:
  base_url: !secret homeassistant_url
  api_password: !secret http_password
#  ssl_certificate: !secret ssl_cert
#  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
recorder:
  purge_interval: 1
  purge_keep_days: 2
      
history:

# View all events in a logbook
#logbook:

# Log Settings
logger:
  default: warn
  logs:
    homeassistant.components.climate: critical
    homeassistant.components.cover.main_garage: fatal
    homeassistant.components.binary_sensor: critical

# Track the sun
sun:

#################################################################
## Components
#################################################################
hue:
  bridges:
    - host: 192.168.1.9
      allow_unreachable: True
      allow_hue_groups: false
light:
  - platform: mqtt
    schema: json
    name: "Cabinet Lights"
    state_topic: "bruh/cabinetlights"
    command_topic: "bruh/cabinetlights/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: group
    name: Upstairs Living Room Lights
    entities:
      - light.upstairslr1
      - light.upstairslr2
      - light.upstairslr3
  - platform: group
    name: Downstairs Living Room Lights
    entities:
      - light.downstairslr1
      - light.downstairslr2
  - platform: group
    name: Office Lights
    entities:
      - light.office_lamp_1
      - light.marissa_desk
  - platform: group
    name: Master Bedroom Lights
    entities:
      - light.masterbr1
      - light.masterbr2
  - platform: group
    name: Kitchen Lights
    entities:
      - light.cabinet_lights

ecobee:
  api_key: !secret ecobee_api_key

apple_tv:
  - name: apple_tv
    host: 192.168.1.15
    login_id: !secret apple_tv_login_id
    credentials: !secret apple_tv_credentials
  - name: apple_tv_4k
    host: 192.168.1.34
    login_id: !secret apple_tv_login_id
    credentials: !secret apple_tv_4k_credentials

rachio:
  api_key: !secret rachio_key
  manual_run_mins: 10

switch:
  - platform: tplink
    host: 192.168.1.11
    name: 'Switch 1'
  - platform: tplink
    host: 192.168.1.22
    name: 'Switch 2'
  - platform: tplink
    host: 192.168.1.23
    name: 'Switch 3'
  - platform: tplink
    host: 192.168.1.29
    name: 'Energy Switch 1'
  - platform: tplink
    host: 192.168.1.30
    name: 'Energy Switch 2'

ifttt:
  key: !secret ifttt_key

zwave:
  usb_path: /dev/zstick
  network_key: !secret zwave_network_key

cover:
  - platform: myq
    username: !secret email_address
    password: !secret myq_pass
    type: chamberlain

# remote:
#   - platform: harmony
#     name: Living Room
#     host: 192.168.1.12

weblink:
  entities:
    - name: "Plex Requests"
      url: !secret ombi_url
    - name: "PlexPy"
      url: !secret plexpy_url
    - name: "SabNZBD"
      url: !secret sabnzbd_url
    - name: "Unifi"
      url: !secret unifi_url
    - name: "Radarr"
      url: !secret radarr_url
    - name: "Sonarr"
      url: !secret sonarr_url

panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump

mqtt:
  broker: 192.168.1.21
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_pass

alexa:

#################################################################
## Camera Stuff
#################################################################
ffmpeg:

#camera:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#################################################################
## Trackers
#################################################################
device_tracker:
  - platform: unifi
    verify_ssl: false
    username: !secret unifi_user
    password: !secret unifi_pass
    interval_seconds: 10
    detection_time: 60
    consider_home: 240
    monitored_conditions:
      - _last_seen_by_uap
      - last_seen
    new_device_defaults:
      track_new_devices: false

#################################################################
## Notifications
#################################################################
notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

#################################################################
## Zones
#################################################################
zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 240
    icon: mdi:home
  
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 300
    icon: mdi:briefcase

#################################################################
## Includes
#################################################################
sensor: !include sensors.yaml

group: !include groups.yaml

automation old: !include automation.yaml

automation: !include automations.yaml

input_select: !include input_select.yaml

input_boolean: !include input_boolean.yaml

script: !include_dir_merge_named scripts/

input_number: !include input_number.yaml